#!/usr/bin/env python3
"""Generate manifest.js for the offline CXR heatmap reader app.

Usage:
  python tools/make_manifest.py cases.csv manifest.js

Input CSV columns:
  case_id,cxr,ark,eva,raddino

Optional columns:
  ark_name,eva_name,raddino_name
"""
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

DEFAULT_LABELS = [
    "No finding",
    "Tuberculosis",
    "Atelectasis",
    "Calcification",
    "Consolidation",
    "Fibrosis",
    "Nodule",
    "Pleural effusion",
    "Pneumonia",
    "Pneumothorax",
    "Thickened pleura",
    "Lung opacity",
    "Lung cavity",
    "Pulmonary edema",
]


def read_cases(csv_path: Path) -> list[dict]:
    with csv_path.open(newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        required = {"case_id", "cxr", "ark", "eva", "raddino"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Missing required columns: {', '.join(sorted(missing))}")

        cases: list[dict] = []
        for row_num, row in enumerate(reader, start=2):
            case_id = (row.get("case_id") or "").strip()
            if not case_id:
                raise ValueError(f"Row {row_num}: case_id is required")
            cases.append(
                {
                    "case_id": case_id,
                    "cxr": (row.get("cxr") or "").strip(),
                    "heatmaps": [
                        {
                            "model_id": "ark",
                            "display_name": (row.get("ark_name") or "ARK").strip(),
                            "src": (row.get("ark") or "").strip(),
                        },
                        {
                            "model_id": "eva",
                            "display_name": (row.get("eva_name") or "EVA").strip(),
                            "src": (row.get("eva") or "").strip(),
                        },
                        {
                            "model_id": "raddino",
                            "display_name": (row.get("raddino_name") or "RADDINO").strip(),
                            "src": (row.get("raddino") or "").strip(),
                        },
                    ],
                }
            )
        return cases


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print("Usage: python tools/make_manifest.py cases.csv manifest.js", file=sys.stderr)
        return 2

    input_csv = Path(argv[1])
    output_js = Path(argv[2])
    cases = read_cases(input_csv)
    config = {
        "studyId": "cxr_gradcam_reader_study",
        "studyTitle": "CXR Heatmap Reader Study",
        "studySubtitle": "Initial diagnosis vs. Grad-CAM-assisted diagnosis",
        "randomizeCaseOrder": True,
        "randomizeHeatmapOrder": True,
        "blindModelNames": True,
        "askHelpfulHeatmaps": True,
        "diagnosisExclusiveLabels": ["No finding"],
        "confidenceLevels": [
            {"value": "1", "label": "1 - Very unsure"},
            {"value": "2", "label": "2 - Somewhat unsure"},
            {"value": "3", "label": "3 - Moderately confident"},
            {"value": "4", "label": "4 - Confident"},
            {"value": "5", "label": "5 - Very confident"},
        ],
        "labels": DEFAULT_LABELS,
        "cases": cases,
    }

    output_js.write_text(
        "/* Generated by tools/make_manifest.py. Do not include ground-truth labels here. */\n"
        "window.APP_CONFIG = " + json.dumps(config, indent=2, ensure_ascii=False) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {output_js} with {len(cases)} cases")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
